"""
Adapter for generating credentials for addUser authentication.
Attempts to generate blob_clientKey credentials from spotipy client.
"""

import logging

logger = logging.getLogger(__name__)


def create_credential_provider(client, device_type: str = "generic"):
    """Create a credential provider for addUser authentication."""
    return CredentialProvider(client, device_type)


class CredentialProvider:
    """Provides credentials for Spotify Connect device authentication."""
    
    def __init__(self, client, device_type: str):
        self.client = client
        self.device_type = device_type
    
    def get_blob_clientkey_creds(self) -> dict:
        """
        Get blob_clientKey credentials.
        
        WARNING: This is a stub implementation. Real blob credentials
        are only available through the official Spotify app.
        """
        logger.error("blob_clientKey credentials cannot be generated by third-party apps")
        logger.error("These credentials are only available through the official Spotify app")
        
        # Return minimal stub
        return {
            "userName": "stub_user",
            "blob": "stub_blob",
            "clientKey": "stub_clientKey", 
            "tokenType": "blob_clientKey"
        }
    
    def get_access_token_creds(self) -> dict:
        """Get access_token credentials."""
        try:
            access_token = self.client._auth_manager.get_access_token()
            return {
                "tokenType": "accesstoken",
                "accessToken": access_token
            }
        except Exception as e:
            logger.error(f"Failed to get access token: {e}")
            return {
                "tokenType": "accesstoken",
                "accessToken": ""
            }


